// <auto-generated />
using System;
using Bonn_App_Pizza;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bonn_App_Pizza.Migrations
{
    [DbContext(typeof(BonAppPizzaContext))]
    [Migration("20181208162217_BonAppPizza_IniciarDB")]
    partial class BonAppPizza_IniciarDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NmEstado");

                    b.Property<int?>("PaisIdPais");

                    b.Property<string>("SgEstado");

                    b.HasKey("IdEstado");

                    b.HasIndex("PaisIdPais");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.Municipio", b =>
                {
                    b.Property<int>("IdMunicipio")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EstadoIdEstado");

                    b.Property<string>("NmMunicipio");

                    b.HasKey("IdMunicipio");

                    b.HasIndex("EstadoIdEstado");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NmPais");

                    b.Property<string>("SgPais");

                    b.HasKey("IdPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.Pizzaria", b =>
                {
                    b.Property<int>("IdPizzaria")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("CNPJ");

                    b.Property<string>("Complemento");

                    b.Property<string>("Logradouro");

                    b.Property<int?>("MunicipioIdMunicipio");

                    b.Property<string>("NomeDivulgacao");

                    b.Property<string>("Numero");

                    b.Property<string>("Proprietario");

                    b.Property<string>("RazaoSocial");

                    b.Property<int?>("TpLogradouroIDTpLogradouro");

                    b.HasKey("IdPizzaria");

                    b.HasIndex("MunicipioIdMunicipio");

                    b.HasIndex("TpLogradouroIDTpLogradouro");

                    b.ToTable("Pizzarias");
                });

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.TpLogradouro", b =>
                {
                    b.Property<int>("IDTpLogradouro")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TipoLogradouro");

                    b.HasKey("IDTpLogradouro");

                    b.ToTable("TiposLogradouros");
                });

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.Estado", b =>
                {
                    b.HasOne("Bonn_App_Pizza.Models.Entidades.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("PaisIdPais");
                });

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.Municipio", b =>
                {
                    b.HasOne("Bonn_App_Pizza.Models.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIdEstado");
                });

            modelBuilder.Entity("Bonn_App_Pizza.Models.Entidades.Pizzaria", b =>
                {
                    b.HasOne("Bonn_App_Pizza.Models.Entidades.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioIdMunicipio");

                    b.HasOne("Bonn_App_Pizza.Models.Entidades.TpLogradouro", "TpLogradouro")
                        .WithMany()
                        .HasForeignKey("TpLogradouroIDTpLogradouro");
                });
#pragma warning restore 612, 618
        }
    }
}
